# -*- coding: utf-8 -*-
"""Handicap Calculator.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1t1i6k8xqE8PRckROyin_gPqosDLbvr3Y
"""

import heapq
import statistics

print("Welcome to the Handicap Index Calculator based on World Handicap System (WHS)")

scores = [] # list of 20 scores
for i in range(20):
  while True:
    try:
      score_input = input(f"\nEnter score {i + 1} of 20: ")
      score = int(score_input)

      if score < 18 or score > 200 : # score cannot be less than 18 since a 0 on a hole is impossible
        print("Invalid input, score must be at least more than 18")
        continue
      else:
        scores.append(score)
        break # end at 20
    except ValueError:
      print("Invalid Input, Please enter an integer value")

all_scores = list(scores) # list of all 20 scores
n = 8 # number scores necessary to be calculated as best of 20
n_best_scores = heapq.nsmallest(n, all_scores) # lowest 8

top_eight_scores = list(n_best_scores) # list of top eight scores
best_score = float(statistics.mean(top_eight_scores)) # compute as a float for single digit handicaps
handicap = best_score - 72 # assuming the course is a 72 par course

print(f"\n--- Handicap Test Results ---")
print(f"Scores Entered: {scores}")
print(f"Best 8 Rounds: {top_eight_scores}")
print(f"Your Handicap Index is: {handicap:.1f}")

